### ISSUE TITLE
conan user returns error 403 with repo admin user

### ISSUE THREAD

**Issue by ccourtoyaxis** [sonatype-nexus-community/nexus-repository-conan#82]
Hi, we are evaluating Nexus Repository to use mainly for python, debian an conan packages.

On a Dockerized Nexus image behind an nginx TLS reverse proxy I am unable to login using **conan user _username_ -r _remote_ -p _password_** with a user who has a Role with **nx-repository-admin-\*-\*-\***. (This user works for **pypi** and **apt** repositories)

I get the follwoing error:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>403 - Nexus Repository Manager</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>


  <!--[if lt IE 9]>
  <script>(new Image).src="https://packages.axis-canada.com/favicon.ico?3.19.1-01"</script>
  <![endif]-->
  <link rel="icon" type="image/png" href="https://packages.axis-canada.com/favicon-32x32.png?3.19.1-01" sizes="32x32">
  <link rel="mask-icon" href="https://packages.axis-canada.com/safari-pinned-tab.svg?3.19.1-01" color="#5bbad5">
  <link rel="icon" type="image/png" href="https://packages.axis-canada.com/favicon-16x16.png?3.19.1-01" sizes="16x16">
  <link rel="shortcut icon" href="https://packages.axis-canada.com/favicon.ico?3.19.1-01">
  <meta name="msapplication-TileImage" content="https://packages.axis-canada.com/mstile-144x144.png?3.19.1-01">
  <meta name="msapplication-TileColor" content="#00a300">

  <link rel="stylesheet" type="text/css" href="https://packages.axis-canada.com/static/css/nexus-content.css?3.19.1-01"/>
</head>
<body>
<div class="nexus-header">
  <a href="https://packages.axis-canada.com">
    <div class="product-logo">
      <img src="https://packages.axis-canada.com/static/images/nexus.png?3.19.1-01" alt="Product logo"/>
    </div>
    <div class="product-id">
      <div class="product-id__line-1">
        <span class="product-name">Nexus Repository Manager</span>
      </div>
      <div class="product-id__line-2">
        <span class="product-spec">OSS 3.19.1-01</span>
      </div>
    </div>
  </a>
</div>
<div class="nexus-body">
  <div class="content-header">
    <img src="https://packages.axis-canada.com/static/rapture/resources/icons/x32/exclamation.png?3.19.1-01" alt="Exclamation point" aria-role="presentation"/>
    <span class="title">Error 403</span>
    <span class="description">Forbidden</span>
  </div>
  <div class="content-body">
    <div class="content-section">
      Forbidden
    </div>
      </div>
</div>
</body>
</html>
```

Here is how I created my test instance:

* Built the conan plugin in Docker
* Copied the **nexus-repository-conan-0.0.6-bundle.kar** from the built docker image to the host's plugin folder
* Launch nexus docker compose which is as follows:

```yml
version: '3'
services:
  nginx:
    image: nginx
    ports:
      - '443:443'
      - '5000:5000'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /data/certs:/certs
    links:
      - nexus
    command: [ nginx, '-g', 'daemon off;' ]
  nexus:
    image: sonatype/nexus3
    ports:
      - '8081:8081'
    volumes:
      - /data/nexus-data:/nexus-data
      - /data/plugins:/opt/sonatype/nexus/deploy
```

* I then created my repositories and users
* I also added the **Conan Beare Token Realm** to the **Active Realms** list

If I try to connect with an invalid user I do get the `ERROR: Wrong user or password. [Remote: axis-release]`. So I beleive the authentication works, but somehow permissions are not evaluated correctly.
